language: php
env:
  global:
    - http_proxy: "http://proxy.wdf.sap.corp:8080"
    - HTTP_PROXY: "http://proxy.wdf.sap.corp:8080"
    - https_proxy: "http://proxy.wdf.sap.corp:8080"
    - HTTPS_PROXY: "http://proxy.wdf.sap.corp:8080"
    - ftp_proxy: "http://proxy.wdf.sap.corp:8080"
    - FTP_PROXY: "http://proxy.wdf.sap.corp:8080"
    - no_proxy: "*.local,169.254/16,*.sap.corp,*.corp.sap"
    - NO_PROXY: "*.local,169.254/16,*.sap.corp,*.corp.sap"
    - OCTOKIT_API_ENDPOINT: "https://github.wdf.sap.corp/api/v3/"

php:
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --no-interaction
  - bin/install-phalcon.sh 3.0.x

script:
  - php -r "echo \Phalcon\Version::get();"
  - vendor/bin/phpunit
  - DATE=`date +%Y-%m-%d_%H-%M-%S`; curl -v 2 --noproxy github.wdf.sap.corp -X POST --insecure -H "Content-Type:application/x-sharedlib" -H "Authorization:token $GITHUB_TOKEN" --data-binary /home/travis/.phpenv/versions/7.0.9/include/php/phalcon.so "https://github.wdf.sap.corp/api/uploads/repos/d060690/phalcon-ci-installer/releases/6387/assets?name=phalcon_$DATE.so"

notifications:
  email: false

